CREATE TABLE CART (
	id UUID PRIMARY KEY UNIQUE, 
	to_user INT, 
	to_tax_country INT,
	created_at DATETIME,
	updated_at DATETIME,
	status VARCHAR(20)
);

CREATE TABLE PRODUCT (
	id INT PRIMARY KEY,
	to_cart UUID,
	category INT,
	description TEXT,
	price DECIMAL(10,4),
	quantity INT
);

CREATE TABLE TAXCOUNTRY (
	id INT AUTO_INCREMENT PRIMARY KEY,
	country VARCHAR(50),
	tax_rate INT
);

ALTER TABLE CART ADD FOREIGN KEY (to_tax_country) REFERENCES TAXCOUNTRY(id);
ALTER TABLE PRODUCT ADD FOREIGN KEY (to_cart) REFERENCES CART(id);